hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
spring:
  application:
    name: gatewayservice
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

